# generated by datamodel-codegen:
#   filename:  json_schema.json
#   timestamp: 2026-01-13T12:49:54+00:00

from __future__ import annotations
from enum import Enum, IntEnum
from uuid import UUID
from pydantic import BaseModel, Field, confloat
from datetime import date


class DepartmentEnum(Enum):
    Arts_and_Humanities = "Arts and Humanities"
    Science_and_Engineering = "Science and Engineering"
    Life_Sciences = "Life Sciences"


class Credits(IntEnum):
    integer_10 = 10
    integer_20 = 20


class Module(BaseModel):
    id: int | UUID = Field(..., title="Id")
    name: str = Field(..., title="Name")
    professor: str = Field(..., title="Professor")
    credits: Credits = Field(..., title="Credits")
    registration_code: str = Field(..., title="Registration Code")


class Student(BaseModel):
    id: UUID = Field(..., title="Id")
    name: str = Field(..., title="Name")
    date_of_birth: date = Field(..., title="Date Of Birth")
    GPA: confloat(ge=0.0, le=5.0) = Field(..., title="Gpa")
    course: str | None = Field(..., title="Course")
    department: DepartmentEnum
    fees_paid: bool = Field(..., title="Fees Paid")
    modules: list[Module] | None = Field(default_factory=list, title="Modules")
